name: Build Safari Extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Safari Extension
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2'
    
    - name: Build Extension
      run: |
        xcodebuild -project "claude-summarizer.xcodeproj" \
                  -scheme "claude-summarizer (macOS)" \
                  -configuration Release \
                  -sdk macosx \
                  CODE_SIGN_IDENTITY="" \
                  CODE_SIGNING_REQUIRED=NO \
                  CODE_SIGNING_ALLOWED=NO \
                  clean build

    # - name: List Directory Contents
    #   run: |
    #     ls -la
        
    # - name: Package Extension
    #   run: |
    #     mkdir -p builds
    #     cp -R Build/Products/Release/claude-summarizer\ Extension.appex builds/
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: safari-extension
        path: ~/Library/Developer/Xcode/DerivedData/
        retention-days: 5
